# config.yaml
api1:
  api_name: "API 1"
  api_host: "http://localhost"
  api_port: 9001
  downstream: 
    - api_name: "api2"
      api_host: "http://localhost"
      api_port: 9002
    - api_name: "api4"
      api_host: "http://localhost"
      api_port: 9004
api2:
  api_name: "API 2"
  api_host: "http://localhost"
  api_port: 9002
  downstream: 
  - api_name: "api3"
    api_host: "http://localhost"
    api_port: 9003

api3:
  api_name: "API 3"
  api_host: "http://localhost"
  api_port: 9003
  downstream: []

api4:
  api_name: "API 4"
  api_host: "http://localhost"
  api_port: 9004
  downstream: []
